site_name: smw-reader
theme:
  name: material
repo_url: https://github.com/Kugeleis/smw-reader
nav:
  - Home: index.md
  - Changelog: CHANGELOG.md
  - API Reference: reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src/smw_reader]
