name: docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          uv: true

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Build docs (Sphinx)
        run: |
          uv run sphinx-build -b html docs/sphinx docs/sphinx/_build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/sphinx/_build

  deploy-docs:
    needs: build-and-deploy-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
