name: Create GitHub Release and Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*' # Triggers when a tag like v1.0.0 is pushed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a GitHub Release
      id-token: write # Required for trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
